#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Installer variables
_homedir="/var/$app/"
ynh_app_setting_set --key=_homedir --value=$_homedir

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# OPENPROJECT CONFIGURATION
#=================================================
ynh_script_progression "Configuring OpenProject..."

mkdir -p "/etc/openproject/"
_openproject_install_dat="/etc/openproject/installer.dat"

#TODO Not sure about this email sending. To be tested.
cat >> "$_openproject_install_dat"<< EOF
postgres/autoinstall reuse
postgres/db_host 127.0.0.1
postgres/db_port 5432
postgres/db_username $db_user
postgres/db_password $db_pwd
postgres/db_name $db_name
server/autoinstall skip
server/hostname $domain
server/protocol HTTPS
smtp/autoinstall smtp
smtp/authentication none
smtp/host 127.0.0.1
smtp/port 25
smtp/domain $domain
smtp/admin_email admin@$domain
memcached/autoinstall install
openproject/default_language $language

server/hostname $domain
server/ssl no
EOF

ynh_store_file_checksum "$_openproject_install_dat"

chmod 750 "/etc/openproject/"
chmod -R o-rwx "/etc/openproject/"
chown -R $app:$app "/etc/openproject/"

openproject config:set PORT=$port
openproject config:set SERVER_PROTOCOL_FORCE_HTTPS="true"
openproject config:set SERVER_HOSTNAME=$domain
openproject config:set SERVER_PATH_PREFIX=$path
openproject config:set OPENPROJECT_RAILS_RELATIVE_URL_ROOT=$path
openproject config:set RAILS_RELATIVE_URL_ROOT=$path

ynh_hide_warnings openproject configure

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="Web-based project management software" --log="systemd"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="systemd"

if ynh_in_ci_tests; then
	sleep 60
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
