#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression "Restoring various files..."

ynh_restore "/etc/openproject/"

chmod 750 "/etc/openproject/"
chmod -R o-rwx "/etc/openproject/"
chown -R $app:$app "/etc/openproject/"

ynh_hide_warnings openproject config:set PORT=$port
ynh_hide_warnings openproject config:set SERVER_PROTOCOL_FORCE_HTTPS="true"
ynh_hide_warnings openproject config:set SERVER_HOSTNAME=$domain
ynh_hide_warnings openproject config:set SERVER_PATH_PREFIX=$path

ynh_hide_warnings openproject configure >> "$YNH_STDINFO"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

yunohost service add $app --description="Web-based project management software" --log=systemd

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

if ynh_in_ci_tests; then
	sleep 60
fi

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
